# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/" # Location of package manifests
    target-branch: main
    schedule:
      interval: "daily"
    pull-request-branch-name:
      separator: "/"
    labels:
      - "npm dependencies"
    commit-message:
      prefix: "dependabot:"
    ignore:
      - dependency-name: "*"
        update-types: ["version-update:semver-major"]
    open-pull-requests-limit: 15

     # Configuration for Python dependencies
  - package-ecosystem: "pip"
    directory: "/lib/lambda_functions" 
    target-branch: main
    schedule:
      interval: "monthly"
    pull-request-branch-name:
      separator: "/"
    labels:
      - "python dependencies"
    commit-message:
      prefix: "dependabot:"
    open-pull-requests-limit: 15
